import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - Create an ordered group of docs
 - Render a sidebar for each doc of that group
 - Provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Custom sidebar for docs - showing main sections
  // Excluding: papers, interventions, partners, symptoms, training
  docs: [
    {
      type: 'category',
      label: 'Recipes',
      items: [{type: 'autogenerated', dirName: 'recipes'}],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Foods',
      items: [{type: 'autogenerated', dirName: 'foods'}],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Biological Targets Overview',
      items: [{type: 'autogenerated', dirName: 'biological-targets'}],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Substances',
      items: [{type: 'autogenerated', dirName: 'substances'}],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Therapeutic Areas',
      items: [{type: 'autogenerated', dirName: 'therapeutic-areas'}],
      collapsed: true,
    },
  ],
};

export default sidebars;
