import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import matter from 'gray-matter';
import os from 'node:os';
import path from 'node:path';
import {deriveFmKcUnion,reconcileFmKcPools} from './lib/fm-supporting-kc-pools.mjs';
import {deriveAdjudicatedFmKcSummary,renderAdjudicatedFmKcSummary} from './lib/fm-kc-relationship-summary.mjs';
import {validateKcDistinctnessReview} from './lib/kc-relationship-distinctness-review.mjs';
const root=process.cwd(),file='docs/biological-targets/brs2/fm1/brs2-fm1-methylation-cycle-efficiency.mdx';
const fm=matter(fs.readFileSync(file,'utf8')),derived=deriveFmKcUnion(fm.data,root);
test('FM1 derives four individually adjudicated connections and preserves the PM2 conditional boundary',()=>{assert.equal(derived.relationships.length,4);assert.deepEqual(derived.relationships.map(r=>r.relationship_type),['supported-upstream-supply','conditional-constraint','supported-upstream-supply','supported-upstream-supply']);assert.deepEqual(derived.relationships,fm.data.fm_kc_relationship_summary);assert.deepEqual(reconcileFmKcPools(file,{rootDir:root}).issues,[]);assert.match(derived.relationships[1].limitation,/eight-man depletion/);});
test('membership, unmatched type, unresolved status and downstream references do not admit an FM connection',()=>{for(const mutate of [r=>{r.data.pm_kc_relationships=[]},r=>{r.data.kc_applicability_adjudications=[]},r=>{for(const a of r.data.kc_applicability_adjudications)a.disposition='unresolved'},r=>{for(const a of r.data.kc_applicability_adjudications)a.applicability_mode='different'}]){const records=structuredClone(derived.pmRecords);records.forEach(mutate);assert.deepEqual(deriveAdjudicatedFmKcSummary(records),[]);}});
test('missing limitations, missing Findings and unknown bibliography keys block a supposedly admitted summary',()=>{for(const mutate of [r=>{r.evidence_limitation=''},r=>{r.evidence_source.finding_ids=['missing']},r=>{r.evidence_source.citation_keys=['missing']}]){const records=structuredClone(derived.pmRecords);mutate(records[0].data.pm_kc_relationships[0]);assert.throws(()=>deriveAdjudicatedFmKcSummary(records));}});
test('FM public summary links to each target PM bibliography and does not convert supply into reliance',()=>{const html=renderAdjudicatedFmKcSummary(derived.relationships);assert.doesNotMatch(html,/Relied upon by/);for(const r of derived.relationships){assert.ok(html.includes(r.limitation));for(const c of r.citations)assert.ok(html.includes(c.href));}});
test('PM1 and PM2 preserve applicability while consolidating identical provision disclosures',()=>{for(const record of derived.pmRecords.slice(0,2)){const r=record.data.pm_kc_relationships[0];assert.equal(r.public_disclosure,'consolidated-as-duplicate');assert.doesNotMatch(record.content,/No mapping established\./);for(const c of r.constituent_relationships){assert.ok(record.data.dietary_input_traceability.some(a=>a.atom_id===c.pm_atom_id));assert.equal(c.public_disclosure,'consolidated-as-duplicate');}}});

test('the recorded final distinctness review includes all newly assessed constituent edges and rejects a duplicate public reprint',()=>{const review=JSON.parse(fs.readFileSync('system/brs2-fm1-kc1-distinctness-review.json','utf8'));assert.deepEqual(validateKcDistinctnessReview(review),[]);assert.equal(review.rows.length,6);const bad=structuredClone(review);bad.publicIds.push(bad.rows[0].relationship_id);assert.ok(validateKcDistinctnessReview(bad).some(i=>/remains public/.test(i.message)));});

test('stale limits and an unrelated top inventory cannot bypass the typed reconciliation gate',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'fm-kc-adjudication-'));try{const p=path.join(dir,'fm.mdx');const bad=structuredClone(fm.data);bad.fm_kc_relationship_summary[0].limitation='Unbounded replacement';bad.key_constraints=[];fs.writeFileSync(p,matter.stringify(fm.content,bad));const codes=reconcileFmKcPools(p,{rootDir:root}).issues.map(i=>i.code);assert.ok(codes.includes('fm_kc_relationship_summary_stale'));assert.ok(codes.includes('fm_kc_inventory_not_adjudicated'));}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('FM1 regeneration preserves the repaired consequence account and all numbered source destinations',async()=>{const {replaceFmSection4}=await import('./lib/fm-integrated-narrative.mjs');const {validateFmSynthesisLayout}=await import('./lib/fm-synthesis-layout.mjs');assert.deepEqual(validateFmSynthesisLayout(fm.data,fm.content),[]);assert.equal(replaceFmSection4(fm.content,fm.data),fm.content);for(const [,n] of fm.content.matchAll(/\]\(#fm-ref-(\d+)\)/g)){assert.ok(fm.data.references[Number(n)-1]);assert.ok(fm.content.includes(`id="fm-ref-${n}"`));}});
