import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import matter from 'gray-matter';
import {validateKcDistinctnessReview} from './lib/kc-relationship-distinctness-review.mjs';
import {validateDietaryLeverAtoms} from './lib/dietary-lever-atoms.mjs';import {validatePmKcGovernance,validateConstituentIdentityRecords,buildCanonicalKcIndex} from './lib/kc-evidence-governance.mjs';import {validatePmReferenceIntegrity} from './lib/pm-reference-index.mjs';import {buildDietaryLeverDisclosureMap} from './lib/dietary-lever-disclosure.mjs';import {buildUpstreamResourceProjection} from '../src/data/dietaryOriginProjection.mjs';
const load=p=>matter(fs.readFileSync(p,'utf8')),pmPath='docs/biological-targets/brs2/fm2/brs2-fm2-pm5-transsulfuration-pathway.mdx',kcPath='docs/biological-targets/brs2/kc/brs2-kc2-methionine-transsulfuration-substrate-pool.mdx',pm=load(pmPath),kc=load(kcPath),registry=JSON.parse(fs.readFileSync('registry/substances.json','utf8'));const page=(p,m)=>({permalink:'/docs/'+p.replace(/^docs\//,'').replace(/\.mdx?$/,''),frontMatter:m.data});const substancePages=['methionine','vitamin-b6'].map(id=>page('docs/substances/'+registry[id].path,load('docs/substances/'+registry[id].path)));const context={registry,substancePages,canonicalKcIndex:buildCanonicalKcIndex([kc.data]),content:pm.content};
test('PM5 evidence, admission, canonical identities and references validate',()=>{for(const fn of [validateDietaryLeverAtoms,validatePmKcGovernance,validateConstituentIdentityRecords]){const issues=[];fn(pm.data,issues,context);assert.deepEqual(issues,[]);}const issues=[];validateConstituentIdentityRecords(kc.data,issues,context);validatePmReferenceIntegrity(pm.data.references,pm.content,issues);assert.deepEqual(issues,[]);});
test('existing biochemical participants and two dietary classifications remain; all disclosures resolve descriptions and Findings',()=>{const values=[...buildDietaryLeverDisclosureMap(pm.data).values()];for(const title of ['Homocysteine','Serine','Cystathionine'])assert.ok(values.some(d=>d.title===title&&d.presentationSection==='3.1.2'));for(const d of values)assert.ok(d.readerDescription&&d.supportingFinding&&d.evidenceReferences.length&&d.evidenceLimitation);assert.equal(pm.data.dietary_lever_atoms[0].requirement_classification,'direct');assert.equal(pm.data.dietary_lever_atoms[1].requirement_classification,'derived');});
test('only independently admitted methionine projects; no cysteine/KC1 inheritance and limitation survives',()=>{const docs=[page(pmPath,pm),page(kcPath,kc),...substancePages];const rows=buildUpstreamResourceProjection(docs,'methionine',registry);assert.equal(rows.length,1);assert.equal(rows[0].relationshipType,'supported-upstream-supply');assert.equal(rows[0].atom.evidence_limitation,pm.data.dietary_input_traceability.at(-1).evidence_limitation);for(const id of ['cysteine','choline','betaine','vitamin-b9'])assert.deepEqual(buildUpstreamResourceProjection(docs,id,registry),[]);});

test('final KC review compares all three sections and does not count pool summary as another job',()=>{const id='PM5-KC2-METHIONINE-SUPPLY';const rows=[{relationship_id:id,disposition:'distinct',biological_job:'Upstream methionine-cycle sulfur provision',compared_biological_jobs:['PLP cofactor provision','Immediate CBS/CGL substrate participation'],compared_records:{'3.1.1':['PM5-DIT-1','PM5-DIT-2'],'3.1.2':['PM5-DIT-3','PM5-DIT-4','PM5-DIT-5'],'3.2':[]},rationale:'Supported upstream supply, not a separate capacity constraint. Only methionine is admitted; pool is its summary.',evidence_source:{finding_ids:['PM5-F5','PM5-F1','PM5-F2']}}];assert.deepEqual(validateKcDistinctnessReview({candidateIds:[id],rows,publicIds:[id]}),[]);const values=[...buildDietaryLeverDisclosureMap(pm.data).values()];assert.equal(values.filter(d=>d.title==='Methionine').length,1);assert.ok(!values.some(d=>d.title==='Methionine'&&d.presentationSection!=='3.1.3'));});
