import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import matter from 'gray-matter';
import {buildUpstreamResourceProjection} from '../src/data/dietaryOriginProjection.mjs';
import {buildDietaryLeverDisclosureMap} from './lib/dietary-lever-disclosure.mjs';
import {validateConstituentIdentityRecords,validatePmKcGovernance,validateKcOwnedEvidence,buildCanonicalKcIndex} from './lib/kc-evidence-governance.mjs';
import {validateDietaryLeverAtoms} from './lib/dietary-lever-atoms.mjs';
import {validatePmReferenceIntegrity} from './lib/pm-reference-index.mjs';
const pmPath='docs/biological-targets/brs2/fm1/brs2-fm1-pm3-same-synthesis.mdx',kcPath='docs/biological-targets/brs2/kc/brs2-kc1-one-carbon-donor-pool.mdx';const load=p=>matter(fs.readFileSync(p,'utf8'));const pm=load(pmPath),kc=load(kcPath);const registry=JSON.parse(fs.readFileSync('registry/substances.json','utf8'));const page=(p,m)=>({permalink:'/docs/'+p.replace(/^docs\//,'').replace(/\.mdx?$/,''),frontMatter:m.data});const substancePages=['vitamin-b9','betaine','choline'].map(id=>page('docs/substances/'+registry[id].path,load('docs/substances/'+registry[id].path)));const docs=[page(pmPath,pm),page(kcPath,kc),...substancePages];
test('canonical PM3/KC1 evidence, identities and numbered references validate',()=>{for(const [data,fn] of [[pm.data,validateDietaryLeverAtoms],[pm.data,validatePmKcGovernance],[kc.data,validateKcOwnedEvidence],[pm.data,validateConstituentIdentityRecords],[kc.data,validateConstituentIdentityRecords]]){const issues=[];fn(data,issues,{entityLabel:'pilot',registry,substancePages,canonicalKcIndex:buildCanonicalKcIndex([kc.data]),content:data===pm.data?pm.content:kc.content});assert.deepEqual(issues,[]);}const references=[];validatePmReferenceIntegrity(pm.data.references,pm.content,references);assert.deepEqual(references,[]);});
test('§3.1.2 biochemical records are unchanged; pool and all three individual disclosures occupy §3.1.3',()=>{const map=buildDietaryLeverDisclosureMap(pm.data),values=[...map.values()];const biochemical=values.filter(d=>d.presentationSection==='3.1.2');assert.deepEqual(biochemical.map(d=>d.title),['Methionine','ATP','Magnesium ions (Mg²⁺)','Potassium ions (K⁺)']);const kcDisclosures=values.filter(d=>d.presentationSection==='3.1.3');assert.equal(kcDisclosures.length,4);for(const d of kcDisclosures){assert.ok(d.readerDescription&&d.biologicalRole&&d.evidenceReferences.length&&d.evidenceLimitation&&d.supportingFinding.id==='PM3-F4');assert.ok(d.originTag);assert.ok(!d.requirementClassification);}assert.equal(pm.data.kc_applicability_adjudications.find(a=>a.kc_id==='BRS2(KC2)').disposition,'unresolved');});
test('all three verified identities project only their admitted PM-specific upstream supply and limitations',()=>{for(const id of ['vitamin-b9','betaine','choline']){const rows=buildUpstreamResourceProjection(docs,id,registry);assert.equal(rows.length,1);assert.equal(rows[0].relationshipType,'supported-upstream-supply');assert.equal(rows[0].atom.evidence_limitation,pm.data.dietary_input_traceability.find(a=>a.substance_id===id).evidence_limitation);assert.equal(rows[0].parentBrs,'BRS2');}assert.deepEqual(buildUpstreamResourceProjection(docs,'vitamin-b12',registry),[]);});
test('pool admission alone, uncertain identity, excluded membership or missing individual admission cannot project',()=>{for(const change of [d=>{d[0].frontMatter.pm_kc_relationships[0].constituent_relationships.find(i=>i.substance_id==='choline').disposition='unresolved';},d=>{d[1].frontMatter.individual_key_constraints.find(i=>i.substance_id==='choline').registration_status='pending-identity';},d=>{d[1].frontMatter.kc_input_traceability.find(a=>a.substance_id==='choline').ikc_membership='excluded';},d=>{d.find(a=>a.frontMatter.id==='choline').frontMatter.id='wrong-identity';},d=>{d[0].frontMatter.kc_applicability_adjudications=[];}]){const bad=structuredClone(docs);change(bad);assert.deepEqual(buildUpstreamResourceProjection(bad,'choline',registry),[]);}});
test('preview or linked downstream PMs do not inherit admission',()=>{const downstream=structuredClone(docs[0]);downstream.frontMatter.pm_id='BRS2-FM1-PM4';delete downstream.frontMatter.pm_kc_relationships;const draft=structuredClone(docs[0]);draft.permalink='/docs/system/stage2b-preview/test';assert.equal(buildUpstreamResourceProjection([...docs,downstream,draft],'choline',registry).length,1);});
test('major identity flags require repair actions; §3.1.2 placement is rejected',()=>{const missing=structuredClone(pm.data);const atom=missing.dietary_input_traceability.find(a=>a.input==='Betaine');atom.canonical_identity={status:'missing-substance',severity:'MAJOR'};missing.pending_actions=[];const issues=[];validateConstituentIdentityRecords(missing,issues,{registry,substancePages});assert.ok(issues.some(i=>i.code==='pm_ikc_identity_repair_action_missing'));const wrong=structuredClone(pm.data);wrong.pm_kc_relationships[0].constituent_relationships[0].presentation_section='3.1.2';const placed=[];validateConstituentIdentityRecords(wrong,placed,{registry,substancePages});assert.ok(placed.some(i=>i.code==='pm_ikc_wrong_section'));});

test('documented §3.1.3 example reproduces real renderer and matrix output using canonical dependencies',()=>{const contract=fs.readFileSync('system/dietary-input-traceability-contract.md','utf8');const fenced=contract.split('<!-- pm3-ikc-record-example -->')[1].split('<!-- /pm3-ikc-record-example -->')[0];const example=JSON.parse(fenced.match(/```json\n([\s\S]*?)\n```/)[1]);const fixture={...pm.data,...example};const map=buildDietaryLeverDisclosureMap(fixture);assert.equal([...map.values()].filter(d=>d.presentationSection==='3.1.3').length,4);const fixtureDocs=[{...docs[0],frontMatter:fixture},...docs.slice(1)];for(const id of ['vitamin-b9','betaine','choline']){assert.equal(buildUpstreamResourceProjection(fixtureDocs,id,registry).length,1);}const modified=structuredClone(fixtureDocs);modified[0].frontMatter.pm_kc_relationships[0].constituent_relationships.find(r=>r.substance_id==='betaine').disposition='unresolved';assert.equal(buildUpstreamResourceProjection(modified,'betaine',registry).length,0);});
